In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# LIBRERIAS DE VISUALIZACION QUE GENERAN GRAFICOS INTERACTIVOS
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.subplots as sp
from plotly.subplots import make_subplots

# RENDERUIZAR LOS GRAFICOS DE PLOTLY EN EL NAVEGADOR
pio.renderers.default = "notebook_connected"

In [25]:
df_salud = pd.read_csv("../DATASETS/heart.csv")
df_salud

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

**INICIO DE LA EXPLORACIÓN DE LOS DATOS**

In [26]:
# CONTAR LA CANTIDAD DE DATOS NULOS EN CADA COLUMNA
df_salud.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

**NO HAY DATOS NULOS**

In [27]:
# COMPROBAR LOS TIPOS DE DATOS DE CADA COLUMNA
df_salud.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

**SE ENCUENTRA BIEN ASIGNADO LOS TIPOS DE DATOS**

In [28]:
# ESTADISTICAS DESCRIPTIVAS DE LAS VARIABLES NUMERICAS
df_salud.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

**RENOMBRAR LAS COLUMNAS DEL DATAFRAME COMO SE ENCUENTRAN EN EL JSON**

In [29]:
# ASIGNAR LOS NOMBRES QUE SE ENCUENTRAN EN EL ARCHIVO JSON A LAS COLUMNAS DEL DATASET

# INICIALMENTE SE IMPORTAN LAS LIBRERIAS PARA LEER EL ARCHIVO JSON
import json
import os

# LEER EL JSON
with open("../NOMBRE DE COLUMNAS/Nombres.json", "r", encoding="utf-8") as f:
    column_names = json.load(f)
    column_names = list(column_names.values())  # CONVERTIR LOS VALORES DEL JSON EN UNA LISTA

# ASIGNAR LOS NUEVOS NOMBRES
df_salud.columns = column_names

# MOSTRAR DATAFRAME
df_salud

,Edad_Paciente,Genero_Paciente,Tipo_Dolor_Pecho,Presion_Arterial_Reposo,Colesterol_Serico,Azucar_Sangre_En_Ayunas,Resultados_Electrocardiograma,Frecuencia_Cardiaca_Maxima,Angina_Ejercicio,Depresion_ST_Ejercicio,Pendiente_Segmento_ST,Numero_Vasos_Filtrados,Talasemia,Enfermedad_Cardiaca
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

**VISUALIZACIÓN DE LOS DATOS**

In [30]:
# VISUALIZAR LA EDAD PROMEDIO DE LOS PACIENTES CON ENFERMEDADES CARDIACAS AGRUPADO POR GENERO
pacientes_con_enfermedades = df_salud[df_salud["Enfermedad_Cardiaca"] == 1]
edad_promedio_por_genero = pacientes_con_enfermedades.groupby("Genero_Paciente")["Edad_Paciente"].mean().reset_index().replace({
    "Genero_Paciente": {
        0: "Mujeres", 
        1: "Hombres"
        }
    })
edad_promedio_por_genero["Edad_Paciente"] = edad_promedio_por_genero["Edad_Paciente"].astype(int)
edad_promedio_por_genero

  Genero_Paciente  Edad_Paciente
0         Mujeres             54
1         Hombres             50

In [31]:
# SE GENERA UN GRAFICO DE BARRAS DE LA TABLA ANTERIOR UTILIZANDO PLOTLY
grafico_edad_promedio = px.bar(edad_promedio_por_genero, x="Genero_Paciente", y="Edad_Paciente", color="Genero_Paciente",
                              title="Edad Promedio de Pacientes con Enfermedades Cardiacas por Género",
                              labels={"Genero_Paciente": "Género del Paciente", "Edad_Paciente": "Edad Promedio"})
grafico_edad_promedio.show()

**CONCLUSIONES:** Se observa en nuestro dataset que la edad promedio de las personas con enfermedades cardiacas se encuentran en un rango entre los 50 a 60 años de edad.

In [32]:
# HISTOGRAMA DE LA EDAD DE LOS PACIENTES
histograma_edad = px.histogram(df_salud, x="Edad_Paciente", nbins=20, title="Distribución de la Edad de los Pacientes",
                               labels={
                                   "Edad_Paciente": "Edad del Paciente",
                                   "Enfermedad_Cardiaca": "Enfermedad Cardíaca"
                                },
color="Enfermedad_Cardiaca")
histograma_edad.show()

**CONCLUSIÓN:** En el histograma se puede observar que gran parte de los pacientes en el dataset se encuentran entre los 54 a 60 años de edad, y esos son los que más sufren de enfermedades cardiacas.

In [33]:
# SE GENERA UN GRAFICO EN 3D Presion_Arterial_Reposo, Colesterol_Serico y Frecuencia_Cardiaca_Maxima
dispersion_3d = px.scatter_3d(df_salud, x="Presion_Arterial_Reposo", y="Colesterol_Serico", z="Frecuencia_Cardiaca_Maxima",
                              color="Enfermedad_Cardiaca", labels={
                                  "Presion_Arterial_Reposo": "Presión Arterial en Reposo",
                                  "Colesterol_Serico": "Colesterol Sérico",
                                  "Frecuencia_Cardiaca_Maxima": "Frecuencia Cardíaca Máxima"
                              },
color_continuous_scale=px.colors.sequential.Viridis_r)
# MODIFICAR LAYOUTS COMO EL TITULO Y LOS TITULOS DE LOS EJES
dispersion_3d.update_layout(title="Relación entre Presión Arterial, Colesterol y Frecuencia Cardíaca Máxima",
                            scene=dict(
                                xaxis_title="Presión Arterial en Reposo",
                                yaxis_title="Colesterol Sérico",
                                zaxis_title="Frecuencia Cardíaca Máxima"
                            ),
                            width=800, height=650)
dispersion_3d.show()

**CONCLUSIÓN:** El gráfico de dispersión 3D sugiere que las variables colesterol sérico, presión arterial en reposo y frecuencia cardíaca máxima no presentan una separación visual clara entre pacientes con y sin enfermedad cardíaca. Esto indica que la enfermedad cardíaca probablemente depende de múltiples factores y no únicamente de las variables analizadas..

In [34]:
# GENERAR UNA MATRIZ DE CORRELACION PARA VER LAS RELACIONES ENTRE LAS VARIABLES CON PLOTLY
matriz_correlacion = df_salud.corr()
fig = px.imshow(
    matriz_correlacion,
    text_auto=True,
    aspect="auto",
    color_continuous_scale="aggrnyl",
    title="Matriz de Correlación",
)

# AÑADIR DIMENSIONES (ANCHO Y ALTO) AL GRÁFICO
fig.update_layout(
    width=1460,
    height=600,
)

fig.show()

**CONCLUSIÓN:** Se pueden observar que las variables con mejor relación a determinar si un paciente tiene enfermedad cardiaca son:

* Tipo_Dolor_Pecho

* Frecuencia_Cardiaca_Maxima

* Angina_Ejercicio

* Depresion_ST_Ejercicio

* Numero_Vasos_Filtrados

In [35]:
# SELECCIONAR LAS COLUMNAS MAS RELEVANTES CON SKLEARN
from sklearn.feature_selection import SelectKBest, f_classif

# CON LA X SE VA A ELIMINAR LA COLUMNA OBJETIVO Y CON LA Y SE VA A SELECCIONAR LA COLUMNA OBJETIVO
X = df_salud.drop("Enfermedad_Cardiaca", axis=1)
y = df_salud["Enfermedad_Cardiaca"]

# SE UTILIZA EL METODO SelectKBest PARA SELECCIONAR LAS 6 CARACTERISTICAS MAS RELEVANTES PARA PREDECIR LA ENFERMEDAD CARDIACA
selector = SelectKBest(score_func=f_classif, k=6)

# SE TRANSFORMA LA MATRIZ DE CARACTERISTICAS X Y SE OBTIENEN LOS NOMBRES DE LAS CARACTERISTICAS SELECCIONADAS
X_new = selector.fit_transform(X, y)

# OBTENER LOS NOMBRES DE LAS CARACTERISTICAS SELECCIONADAS
selected_features = X.columns[selector.get_support()]

# SE IMPRIMEN LAS CARACTERISTICAS SELECCIONADAS
print("LOS CAMPOS SELECCIONADOS SON: {} \n".format(selected_features))

# CREAR UN NUEVO DATAFRAME SOLO CON LAS CARACTERÍSTICAS SELECCIONADAS Y LA COLUMNA OBJETIVO
df_salud_seleccionado = df_salud[selected_features.tolist() + ["Enfermedad_Cardiaca"]]
df_salud_seleccionado

LOS CAMPOS SELECCIONADOS SON: Index(['Tipo_Dolor_Pecho', 'Frecuencia_Cardiaca_Maxima', 'Angina_Ejercicio',
       'Depresion_ST_Ejercicio', 'Pendiente_Segmento_ST',
       'Numero_Vasos_Filtrados'],
      dtype='object')

,Tipo_Dolor_Pecho,Frecuencia_Cardiaca_Maxima,Angina_Ejercicio,Depresion_ST_Ejercicio,Pendiente_Segmento_ST,Numero_Vasos_Filtrados,Enfermedad_Cardiaca
0,0,168,0,1.0,2,2,0
1,0,155,1,3.1,0,0,0
2,0,125,1,2.6,0,0,0
3,0,161,0,0.0,2,1,0
4,0,106,0,1.9,1,3,0
...,...,...,...,...,...,...,...
1020,1,164,1,0.0,2,0,1
1021,0,141,1,2.8,1,1,0
1022,0,118,1,1.0,1,1,0
1023,0,159,0,0.0,2,0,1
1024,0,113,0,1.4,1,1,0

**POR ÚLTIMO SE VA A EXPORTAR EL DATASET FINAL CON LAS COLUMNAS RENOMBRADAS**

In [36]:
df_salud_seleccionado.to_csv("../DATASETS/df_enfermedades_cardiacas.csv", index=False)